# Generated by Django 5.1.2 on 2024-11-26 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_reviews_id_reviews_review_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'reviews'},
        ),
    ]
